name: Keep Streamlit awake

on:
  schedule:
    - cron: '*/7 * * * *'   # cada 5 min (UTC)
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    env:
      WARMUP_URL: "https://recomendadorturisticointeligente-ltledqrz5j9w5acwqdwask.streamlit.app/?warmup=1"
    steps:
      - name: Jitter corto y ping con follow-redirects
        shell: bash
        run: |
          # Espera aleatoria 0..90s para desincronizar sin crear huecos
          J=$(( RANDOM % 91 ))
          echo "Esperando ${J}s antes del ping..."
          sleep $J

          # HEAD rápido para “tocar” la app
          STATUS_HEAD=$(curl -s -o /dev/null -w "%{http_code}" -m 10 -L -I -A "Mozilla/5.0 keepalive" "$WARMUP_URL" || true)
          echo "HTTP status (HEAD): $STATUS_HEAD"

          # GET real para calentar (load_models y cachés)
          STATUS_GET=$(curl -s -o /dev/null -w "%{http_code}" -m 15 -L -A "Mozilla/5.0 keepalive" "$WARMUP_URL" || true)
          echo "HTTP status (GET): $STATUS_GET"

          # Reintento simple si no fue 2xx
          if [[ "$STATUS_GET" != 2* ]]; then
            echo "Reintentando en 20s..."
            sleep 20
            STATUS_GET2=$(curl -s -o /dev/null -w "%{http_code}" -m 15 -L -A "Mozilla/5.0 keepalive" "$WARMUP_URL" || true)
            echo "HTTP status (GET reintento): $STATUS_GET2"
          fi
